### ISSUE TITLE
Allow the user to specify any type of trigger

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/Akka.Quartz.Actor#1]
It would be nice to allow the user when creating jobs to add any time of trigger. Maybe splitting the job/trigger creation would be a good idea also?
I'm happy to look at this as I know quartz and have used it in other projects.
Cheers
Sean.

**Comment by maxim-s** [comment]
Yes, good idea!
thank you

**Comment by SeanFarrow** [comment]
Hi,
Quartz.net has an IOperableTrigger interface, this serializes fine with JSon.net, does this mean it will serialize with Akka? if so we can just pass this instead of the cron string. That way the user has all the power of the quartz trigger builder.

**Comment by maxim-s** [comment]
Hello,
I've checked looks like ok, I'm going to change ```CreateJob``` command to ```CreateJob<T> : IJobCommand where T : ITrigger```

**Comment by SeanFarrow** [comment]
Makes sense, although, does this really need to be generic, couldn’t we get away with passing the IOperableTrigger in as a parameter?

**Comment by maxim-s** [comment]
Yes it's not necessary. I think to use ITrigger property in the CreateJob class, and in this case we can use both IOperableTrigger and ICronTrigger

**Comment by SeanFarrow** [comment]
Ok, good stuff, there are some other things that I think need looking at, do you want me to raise separate issues?

**Comment by maxim-s** [comment]
Please create separate issue

**Comment by SeanFarrow** [comment]
Did this ever get done?

**Comment by maxim-s** [comment]
@SeanFarrow sure, could you review #6 ?

**Comment by SeanFarrow** [comment]
Looks good, the only thing I would change, for consistency is to rename the cron parameter in the CreateJob messages constructor to trigger.

**Comment by maxim-s** [comment]
@SeanFarrow done, and close via #6
