### ISSUE TITLE
Compilation issues and failing tests

### ISSUE THREAD

**Issue by stevemesser** [akkadotnet/Akka.Quartz.Actor#19]
It would appears that:
CreateJobFail, JobEvent, and RemoveJobFail have been checked in with C# 6 readonly properties which don't compile.

Once I add a private set to these properties, the following tests fail unless I run them by themselves.
1. QuartzActor_Should_Create_Job
2. QuartzPersistentActor_Should_Remove_Job

**Comment by maxim-s** [comment]
close via #20
