### ISSUE TITLE
Use this lib with Akka.Net 1.5

### ISSUE THREAD

**Issue by ingted** [akkadotnet/Akka.Quartz.Actor#274]
Since Match() doesn't work anymore, I need to modify the code like this or it will throw "Could not load type 'Akka.PatternMatch' from assembly 'Akka, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null'."
```
protected override bool Receive(object message)
        {
            if(message is CreateJob c)
            {
                CreateJobCommand(c);
                return true;
            }
            if (message is RemoveJob r)
            {
                RemoveJobCommand(r);
                return true;
            }
            return false;
            //return message.Match().With<CreateJob>(CreateJobCommand).With<RemoveJob>(RemoveJobCommand).WasHandled;
        }
```
and 
```
protected override bool Receive(object message)
        {
            if (message is CreatePersistentJob c)
            {
                CreateJobCommand(c);
                return true;
            }
            if (message is RemoveJob r)
            {
                RemoveJobCommand(r);
                return true;
            }
            return false;
            //return message.Match().With<CreatePersistentJob>(CreateJobCommand).With<RemoveJob>(RemoveJobCommand).WasHandled;
        }
```

**Comment by ingted** [comment]
Just a workaround... I know this modification is ugly...

**Comment by Aaronontheweb** [comment]
@ingted it should be easy to refactor this library to no longer use `PatternMatch` - just need a `switch` statement there instead.

**Comment by ingted** [comment]
Because I returned true and false by myself without WasHandled (just like the modified code above), I think it is a bad modification... So do you think it is ok? If so, I would like to create a PR.

**Comment by Aaronontheweb** [comment]
@ingted we've shipped updates with v1.5 support, so I believe this issue is now resolved.

**Comment by ingted** [comment]
You, Akka.net community andPetabridge are great, love all of you!!!

**Comment by Aaronontheweb** [comment]
> You, Akka.net community andPetabridge are great, love all of you!!!

🙏
