### ISSUE TITLE
Strong typing of Job Not Found

### ISSUE THREAD

**Issue by ncthbrt** [akkadotnet/Akka.Quartz.Actor#29]
Hi there, 
I'm using this framework to schedule timers. 
Users can cancel these timers. It may be possible that multiple attempts are made to cancel a given timer. 
The problem is that at least on the dev branch, when a job is not found, the only way to check if it the remove job fail was sent due to the timer already being cancelled is by performing a string comparison against
`"job not found"`. This is problematic as this means that should this package be updated and the error string be changed, then code will assume failure for other reasons.

**Comment by Danthar** [comment]
issue closed via merge
