### ISSUE TITLE
Akka 1.2.0 compatible?

### ISSUE THREAD

**Issue by ErrCode** [akkadotnet/Akka.Quartz.Actor#32]
Hi,

Will there be a Nuget package release for use with Akka.1.2.0?

**Comment by ncthbrt** [comment]
I would be shocked if there wasn't

**Comment by ncthbrt** [comment]
I'll make a quick PR

**Comment by ncthbrt** [comment]
@ErrCode made PR #33 But I'll need to get @maxim-s to approve the changes

@maxim-s Btw noticed the integration test doesn't appear to be running in CI.

**Comment by maxim-s** [comment]
One moment I'll check, I'm not sure why CI skip integration tests
