### ISSUE TITLE
Allow a user to use an already initialized scheduler

### ISSUE THREAD

**Issue by SeanFarrow** [akkadotnet/Akka.Quartz.Actor#4]
it would be nice if we could allow the user to pass in an already initialized scheduler raas well as props. This would handle the situation where a schedule has already been created and added to a di container.

**Comment by maxim-s** [comment]
@SeanFarrow good idea!

**Comment by SeanFarrow** [comment]
Do you want me to fork/do this?

**Comment by maxim-s** [comment]
@SeanFarrow would be great

**Comment by SeanFarrow** [comment]
Ok, I’ll fork and send a pull request in the next week or so—just updating all by project to Akka 1.1.

**Comment by maxim-s** [comment]
@SeanFarrow :+1:  also I'll update this plugin to Akka 1.1

**Comment by SeanFarrow** [comment]
Ok, I would have done that at the same time!
But I’ll let you do that and treat as a separate issue.

**Comment by SeanFarrow** [comment]
When we do this, should we take out scheduler creation completely? It makes sense that the actor should not create the scheduler.

**Comment by maxim-s** [comment]
@SeanFarrow I think just add one more constructor with scheduler, do you to do it? or I can do it

**Comment by SeanFarrow** [comment]
Hai,

I’m happy to do this in the next few days.
Also, have you started looking at quartz 3?
Cheers
Sean.

**Comment by maxim-s** [comment]
@SeanFarrow thank you, I'll check compatibility issues, but as I know a lot of guys still use 2.x version

**Comment by maxim-s** [comment]
@SeanFarrow  thank you, close via #23
