### ISSUE TITLE
Null reference exception using constructor QuartzPersistentActor(IScheduler scheduler)

### ISSUE THREAD

**Issue by joaopi** [akkadotnet/Akka.Quartz.Actor#42]
Null reference exception using constructor QuartzPersistentActor(IScheduler scheduler):
System.NullReferenceException: Object reference not set to an instance of an object.
   at Akka.Quartz.Actor.QuartzPersistentActor.AddSystemToScheduler()
   at Akka.Quartz.Actor.QuartzPersistentActor..ctor(IScheduler scheduler)
   at AltitudeCloud.JobSchedulerService.Actors.ScheduleActor..ctor(ActorFactory actorFactory, ILog log, IScheduler scheduler) 

parameter scheduler is not null, but because the _scheduler field is private in both QuartzPersistentActor and base class QuartzActor, and is not set in QuartzPersistentActor when the method AddSystemToScheduler is called it uses _scheduler which is obviously null. 

This could be solved either by converting the _scheduler field to `protected` in QuartzActor class (probably the best solution) or by setting `this._scheduler = scheduler` in constructor QuartzPersistentActor(IScheduler scheduler).

**Comment by maxim-s** [comment]
@joaopi thank you, nice catch

**Comment by Arkatufus** [comment]
This is already fixed
