### ISSUE TITLE
Nuget package not found

### ISSUE THREAD

**Issue by Jared314** [akkadotnet/Akka.Quartz.Actor#8]
The [`Akka.Quartz.Actor`](https://www.nuget.org/packages/Akka.Quartz.Actor/) package, specified in the readme, is not found on [nuget.org](https://www.nuget.org/).

**Comment by maxim-s** [comment]
close via #13

**Comment by Jared314** [comment]
The nuget package now exists and installs the dependencies correctly. But, the `Akka.Quartz.Actor.dll` is missing from the package.

**Comment by maxim-s** [comment]
@Jared314  thank you, could you check updates? now it should be solved

**Comment by Jared314** [comment]
@maxim-s Version 1.0.1 fixes the issue. Thank you.
